## Задание

- [x] Выбрать датасет
- [x] Определить задачу аппроксимации
- [x] Разбить датасет на обучающую и экспериментальную выборку
- [x] Провести корреляционный анализ
- [x] Выделить 1-2 переменные, которые влияют на выход
- [x] Разбить переменные на термы (распределить равномерно по графику)
- [x] Реализовать 4 функции принадлежности и для каждой построить графики
- [x] Реализовать машину нечёткого вывода (Синглтон / Мамдани / Такаги-Сугено)

## Данные

В качестве датасета возьмём данные об использовании Инстаграм\*: [Social Media User Analysis](https://www.kaggle.com/datasets/rockyt07/social-media-user-analysis/data).
<br/>Будем аппроксимировать шкалу воспринимаемого стресса (PSS-10 или perceived stress scale).

Разделим датасет на обучающую и экспериментальную выборку в соотношении 70 к 30.

*\* соцсеть Инстаграм признана экстремистской, её деятельность запрещена на территории РФ*

## Корреляционная матрица

Начнём с вычисления корреляции между параметрами. Выберем 3 наиболее коррелирующих с параметром PSS.

In [1]:
%use coroutines
%use dataframe
%use kandy

// read dataset
val rawData = DataFrame.read("data/instagram_usage_lifestyle.csv")
val learnData = rawData.head((rawData.rowsCount() * 0.7).toInt())
val experimentData = rawData.tail((rawData.rowsCount() * 0.3).toInt())
println("""
    Rows total: ${rawData.rowsCount()}
    Rows for learning: ${learnData.rowsCount()}
    Rows for experimental: ${experimentData.rowsCount()}
    """.trimIndent())

// evaluate correlation matrix (using pearson correlation coefficient)
val correlationMatrix = learnData.select { it.all() }.corr()
DISPLAY(correlationMatrix)

// select 3 most correlated params for PSS
val targetColumnName = "perceived_stress_score"
val correlatedColumns: List<String> =
    correlationMatrix.first {
        it["column"] == targetColumnName
    }.let { happinessRow ->
        (happinessRow.columnNames() - "column" - targetColumnName)
            .sortedBy { columnName ->
                (happinessRow[columnName] as Double).absoluteValue
            }.reversed().subList(0, 3)
    }

// show filtered correlation matrix
correlationMatrix.filter {
    it["column"] == targetColumnName
}.select("column", *correlatedColumns.toTypedArray())

Rows total: 1547896
Rows for learning: 1083527
Rows for experimental: 464368

column,user_id,age,exercise_hours_per_week,sleep_hours_per_night,perceived_stress_score,self_reported_happiness,body_mass_index,blood_pressure_systolic,blood_pressure_diastolic,daily_steps_count,weekly_work_hours,hobbies_count,social_events_per_month,books_read_per_year,volunteer_hours_per_month,travel_frequency_per_year,daily_active_minutes_instagram,sessions_per_day,posts_created_per_week,reels_watched_per_day,stories_viewed_per_day,likes_given_per_day,comments_written_per_day,dms_sent_per_week,dms_received_per_week,ads_viewed_per_day,ads_clicked_per_day,time_on_feed_per_day,time_on_explore_per_day,time_on_messages_per_day,time_on_reels_per_day,followers_count,following_count,notification_response_rate,account_creation_year,average_session_length_minutes,linked_accounts_count,user_engagement_score
user_id,"1,000000","-0,001529","-0,000848","0,000513","-0,000993","0,001430","0,000295","0,000217","-0,001184","-0,001283","0,000087","0,000758","0,000385","0,000885","0,000533","-0,000989","-0,001145","-0,001417","0,000405","-0,000464","-0,001399","-0,001084","-0,001318","-0,000643","-0,000812","-0,001573","-0,000874","-0,001157","-0,001203","-0,000565","-0,001605","0,001473","0,001286","0,000895","-0,001458","-0,000795","0,000191","0,001772"
age,"-0,001529","1,000000","-0,001245","0,001742","-0,000561","0,000046","0,001240","-0,000324","0,000152","0,000573","-0,000597","0,000163","0,000967","-0,002103","-0,002182","0,000716","-0,198355","-0,147162","-0,461694","-0,520696","-0,181949","-0,194439","-0,186522","-0,178327","-0,183164","-0,177253","-0,140733","-0,193724","-0,172226","-0,177797","-0,185592","-0,062281","-0,069518","0,000989","0,000790","-0,058114","0,001807","0,112297"
exercise_hours_per_week,"-0,000848","-0,001245","1,000000","0,001461","0,000083","-0,000308","0,000462","0,000224","-0,000585","0,000362","-0,001020","-0,001216","0,002176","-0,000633","-0,001474","-0,000873","0,000439","-0,000376","0,001080","0,000875","0,000758","0,000462","0,000467","-0,000426","0,000206","0,001247","0,000376","0,000211","-0,000373","0,000666","0,000289","-0,001275","-0,001169","0,000796","0,000028","0,002395","0,000032","-0,001907"
sleep_hours_per_night,"0,000513","0,001742","0,001461","1,000000","-0,000881","-0,000540","0,000425","0,001015","-0,000145","-0,000540","-0,000981","0,001001","-0,000736","-0,000042","-0,000837","0,000641","-0,000795","-0,000985","-0,000388","-0,001652","-0,000753","-0,000605","-0,000326","-0,000243","-0,000269","-0,000884","-0,001897","-0,000629","-0,001617","-0,001370","-0,000707","-0,000215","-0,000744","0,000902","-0,000998","0,000820","-0,000769","-0,000070"
perceived_stress_score,"-0,000993","-0,000561","0,000083","-0,000881","1,000000","0,000187","0,001441","0,000110","0,000201","-0,000076","0,000872","0,000300","-0,000128","-0,000257","-0,000445","-0,000293","0,834351","0,624127","0,376826","0,674719","0,813881","0,818492","0,787228","0,749826","0,769421","0,744556","0,592833","0,813425","0,723960","0,749131","0,779347","0,049720","0,057051","0,000005","-0,000110","0,159238","-0,000684","-0,435999"
self_reported_happiness,"0,001430","0,000046","-0,000308","-0,000540","0,000187","1,000000","0,000516","-0,000244","0,000368","-0,000017","-0,001976","-0,000502","0,000633","-0,000496","0,000202","0,000330","-0,372625","-0,277639","-0,133314","-0,295536","-0,344293","-0,365501","-0,351356","-0,334792","-0,343534","-0,331863","-0,264614","-0,363294","-0,323157","-0,334416","-0,348496","-0,017464","-0,019978","-0,000196","0,001166","-0,106418","-0,001203","0,268591"
body_mass_index,"0,000295","0,001240","0,000462","0,000425","0,001441","0,000516","1,000000","-0,000402","-0,001665","-0,001166","0,000001","0,000398","0,001312","-0,001720","-0,000765","0,001708","0,000690","-0,000115","0,001083","-0,000434","0,000927","0,000546","0,000604","0,000527","0,000474","0,000450","0,000022","0,001209","0,001095","0,000876","0,000764","0,000143","0,000614","0,000346","-0,000556","0,000376","-0,000881","-0,000085"
blood_pressure_systolic,"0,000217","-0,000324","0,000224","0,001015","0,000110","-0,000244","-0,000402","1,000000","-0,000318","-0,000731","0,000410","-0,000130","-0,000124","-0,000555","0,000507","-0,000634","0,001087","0,000088","0,000682","0,000802","0,001034","0,001222","0,000989","0,000565","0,001137","0,000610","0,000997","0,001227","0,001640","0,000958","0,001521","0,000981","0,000315","-0,001319","-0,000676","0,000797","-0,000540","-0,001668"
blood_pressure_diastolic,"-0,001184","0,000152","-0,000585","-0,000145","0,000201","0,000368","-0,001665","-0,000318","1,000000","-0,000715","-0,000849","0,001280","0,000701","0,000005","0,000646","-0,000118","0,000317","0,000738","0,001650","0,000114","0,000385","0,000255","0,000587","0,000491","0,000580","0,000598","0,000060","0,000251","0,000340","0,000375","-0,000410","0,000501","0,001323","0,000868","-0,000546","-0,000171","0,001248","-0,000885"
daily_steps_count,"-0,001283","0,000573","0,000362","-0,000540","-0,000076","-0,000017","-0,001166","-0,000731","-0,000715","1,000000","-0,001359","0,000378","-0,001363","0,000810","0,000667","0,000914","-0,000374","0,000540","-0,001227","-0,000919","-0,000479","-0,000104","-0,000090","-0,000271","0,000229","-0,000247","-0,001767","-0,000290","-0,000557","0,000261","-0,000091","-0,000972","-0,000659","-0,001090","0,000781","-0,001259","0,000021","0,000022"
weekly_work_hours,"0,000087","-0,000597","-0,001020","-0,000981","0,000872","-0,001976","0,000001","0,000410","-0,000849","-0,001359","1,000000","-0,000290","0,001346","0,000283","0,000370","0,000040","0,001395","0,000346","0,001150","0,001905","0,001321","0,001328","0,001636","0,001063","0,001706","0,001468","0,000965","0,001577","0,001662","0,001457","0,001034","-0,000858","-0,000137","0,001747","-0,000535","0,000386","-0,000018","-0,000717"
hobbies_count,"0,000758","0,000163","-0,001216","0,001001","0,000300","-0,000502","0,000398","-0,000130","0,001280","0,000378","-0,000290","1,000000","0,000731","0,000083","0,000520","0,000558","0,000332","0,000306","-0,000727","0,000142","-0,000087","0,000423","0,000671","-0,000357","0,000864","0,001281","-0,000830","-0,000401","0,000672","0,000289","-0,000104","-0,000162","-0,000769","0,000398","-0,001325","0,000119","0,000604","0,000010"
social_events_per_month,"0,000385","0,000967","0,002176","-0,000736","-0,000128","0,000633","0,001312","-0,000124","0,000701","-0,001363","0,001346","0,000731","1,000000","0,000820","-0,001295","0,000221","-0,000349","-0,000849","-0,000909","-0,000551","-0,000399","-0,000504","0,000335","-0,001064","0,000248","-0,000372","-0,000882","-0,000153","0,000014","0,000147","0,000028","0,000726","-0,000809","0,000128","-0,001409","0,000027","-0,000083","-0,000907"
books_read_per_year,"0,000885","-0,002103","-0,000633","-0,000042","-0,000257","-0,000496","-0,001720","-0,000555","0,000005","0,000810","0,000283","0,000083","0,000820","1,000000","-0,000799","0,000746","0,000782","0,001076","0,000361","0,001536","0,000626","0,000854","0,000843","0,000598","0,000760","0,000396","-0,000290","0,000948","0,001428","0,001116","0,000622","-0,000031","-0,000225","-0,000481","-0,000451","-0,000190","-0,000301","-0,000933"
volunteer_hours_per_month,"0,000533","-0,002182","-0,001474","-0,000837","-0,000445","0,000202","-0,000765","0,000507","0,000646","0,000667","0,000370","0,000520","-0,001295","-0,000799","1,000000","0,000198","-0,000274","-0,001268","0,000241","0,000256","-0,000422","-0,000262","-0,000077","-0,000051","-0,000107","-0,000888","0,000433","-0,000767","0,000043","-0,000520","-0,000023","-0,000122","-0,000218","-0,000421","0,000595","0,000534","0,000911","0,001526"
travel_frequency_per_year,"-0,000989","0,000716","-0,000873","0,000641","-0,000293","0,000330","0,001708","-0,000634","-0,000118","0,000914","0,000040","0,000558","0,000221","0,000746","0,000198","1,000000","-0,000332","0,000393","-0,000107","-0,000446","-0,000303","-0,000194","-0,000177","-0,000490","0,000265","-0,000433","-0,001090","-0,000304","-0,000553","-0,000101","-0,000718","0,000342","0,000975","-0,001356","-0,001393","-0,001165","0,000579","0,001321"
daily_active_minutes_instagram,"-0,001145","-0,198355","0,000439","-0,000795","0,834351","-0,372625","0,000690","0,001087","0,000317","-0,000374","0,001395","0,000332","-0,000349","0,000782","-0,000274","-0,000332","1,000000","0,748161","0,506155","0,874604","0,955256","0,980921","0,942964","0,898977","0,922258","0,891910","0,710201","0,974871","0,867728","0,897716","0,934284","0,066558","0,076198","0,000135","-0,000591","0,196414","-0,000466","-0,529795"
sessions_per_day,"-0,001417","-0,147162","-0,000376","-0,000985","0,624127","-0,277639","-0,000115","0,000088","0,000738","0,000540","0,000346","0,000306","-0,000849","0,001076","-0,001268","0,000393","0,748161","1,000000","0,379163","0,653699","0,713708","0,733750","0,705316","0,672851","0,690105","0,667039","0,531024","0,729596","0,649116","0,671391","0,698698","0,050227","0,057628","0,000570","-0,000615","-0,342869","0,000578","-0,380927"
posts_created_per_week,"0,000405","-0,461694","0,001080","-0,000388","0,376826","-0,133314","0,001083","0,000682","0,001650","-0,001227","0,001150","-0,000727","-0,000909","0,000361","0,000241","-0,000107","0,506155","0,379163","1,000000","0,626218","0,496328","0,496713","0,477418","0,454967","0,467177","0,451428","0,359426","0,493599","0,438595","0,454491","0,473197","0,133575","0,150915","-0,000908","-0,000883","0,075296","-0,000627","-0,161221"
reels_watched_per_day,"-0,000464","-0,520696","0,000875","-0,001652","0,674719","-0,295536","-0,000434","0,000802","0,000114","-0,000919","0,001905","0,000142","-0,000551","0,001536","0,000256","-0,000446","0,874604","0,653699","0,626218","1,000000","0,850245","0,857783","0,825153","0,786146","0,806949","0,780356","0,620596","0,852746","0,759003","0,785152","0,817171","0,083182","0,094758","-0,000180","-0,000446","0,186926","-0,000934","-0,482087"

column,daily_active_minutes_instagram,likes_given_per_day,stories_viewed_per_day
perceived_stress_score,"0,834351","0,818492","0,813881"

Таким образом, `daily_active_minutes_instagram` (активное время в соцсети), `likes_given_per_day` (поставленные лайки) и `stories_viewed_per_day` (количество просмотренных reels) имеют сильную положительную корреляцию c PSS.
<br/>Визуализируем на графике точки и линейную регрессию:
$$\hat{\beta} = \frac{\sum_{i=1}^{n}(x_i - \bar{x})(y_i - \bar{y})}{\sum_{i=1}^{n}(x_i - \bar{x})^2}$$

In [2]:
import org.jetbrains.kotlinx.kandy.ir.Plot
import org.jetbrains.kotlinx.kandy.util.color.Color

// draw linear regression
/**
 * Columns must be [Int]
 */
fun displayLinearRegression(
    columnXName: String, columnXTitle: String,
    columnYName: String, columnYTitle: String,
    limit: Int = learnData.rowsCount()
) { // y = kx + b
    val x = learnData[columnXName].cast<Int>().toList()
    val y = learnData[columnYName].cast<Int>().toList()

    val meanX = x.average()
    val meanY = y.average()

    val k = x.zip(y).sumOf { (xi, yi) ->
        (xi - meanX) * (yi - meanY)
    } / x.sumOf {
        (it - meanX).pow(2)
    }
    val b = meanY - k * meanX

    val xLine = listOf(x.min().toDouble(), x.max().toDouble())
    val yLine = xLine.map { k * it + b }

    DISPLAY(learnData.head(limit).plot {
        points {
            x(column<Double>(columnXName)) {
                axis.name = columnXTitle
            }
            y(column<Int>(columnYName)) {
                axis.name = columnYTitle
            }
            color = Color.BLUE
        }
        line {
            x(xLine)
            y(yLine)
            color = Color.RED
        }
    })
}

displayLinearRegression(
    "daily_active_minutes_instagram", "Ежедневное использование (мин)",
    targetColumnName, "PSS",
    1000
)
displayLinearRegression(
    "likes_given_per_day", "Количество поставленных лайков (в день)",
    targetColumnName, "PSS",
    1000
)
displayLinearRegression(
    "stories_viewed_per_day", "Количество просмотренных reels",
    targetColumnName, "PSS",
    1000
)

Распределим параметры равномерно по термам.
Ниже приведены формулы разных функций принадлежности, но мы будем использовать только треугольную:

**Треугольная**:
$$
% Треугольная (a, b, c — левая граница, вершина, правая граница)
\mu(x) = \begin{cases}
0, & x \leq a \\
\frac{x - a}{b - a}, & a < x \leq b \\
\frac{c - x}{c - b}, & b < x < c \\
0, & x \geq c
\end{cases}
$$

**Трапецеидальная**:
$$
% Трапецеидальная (a, b, c, d — границы и плато)
\mu(x) = \begin{cases}
0, & x \leq a \\
\frac{x - a}{b - a}, & a < x < b \\
1, & b \leq x \leq c \\
\frac{d - x}{d - c}, & c < x < d \\
0, & x \geq d
\end{cases}
$$

**Параболическая**:
$$
% Параболическая (a, b — границы)
\mu(x) = \begin{cases}
0, & x \leq a \\
1 - \left(\frac{x - b}{b - a}\right)^2, & a < x \leq b \\
1 - \left(\frac{x - b}{c - b}\right)^2, & b < x < c \\
0, & x \geq c
\end{cases}
$$

**Гаусса**:
$$
% Гауссова (c — центр, σ — ширина)
\mu(x) = e^{-\frac{(x - c)^2}{2\sigma^2}}
$$

In [3]:
/* API */

enum class MembershipFunctionType {
    TRIANGULAR,
    TRAPEZOIDAL,
    PARABOLIC,
    GAUSSIAN
}

data class LinguisticVariable(
    val columnName: String,
    val userFriendlyName: String,
    val membershipFunctionType: MembershipFunctionType,
    val termNames: List<String>
) {
    val minValue: Int
    val maxValue: Int

    init {
        learnData[columnName]
            .cast<Int>()
            .toList()
            .run {
                minValue = min()
                maxValue = max()
            }
    }
}

fun interface TermChartBuilder {
    /**
     * [fromX], [toX] - both inclusive
     */
    fun append(
        // input
        fromX: Double,
        toX: Double,
        termName: String,
        // output
        bufferX: MutableList<Double>,
        bufferY: MutableList<Double>,
        bufferTerm: MutableList<String>
    )
}

fun displayTerms(
    variable: LinguisticVariable,
    builder: TermChartBuilder
) {
    val step = (variable.maxValue - variable.minValue) / (variable.termNames.size.toDouble() - 1) * 2
    val fromX = variable.minValue - step / 2

    val bufferX = ArrayList<Double>()
    val bufferY = ArrayList<Double>()
    val bufferTerm = ArrayList<String>()

    variable.termNames.forEachIndexed { i, termName ->
        builder.append(
            fromX + step / 2 * i, fromX + step * (i / 2.0 + 1), termName,
            bufferX, bufferY, bufferTerm
        )
    }

    DISPLAY(learnData.plot {
        layout.title = variable.userFriendlyName
        x.axis.limits = variable.minValue.toDouble() ..  variable.maxValue.toDouble()
        y.axis.limits = 0 .. 1
        line {
            x(bufferX)
            y(bufferY)
            color(bufferTerm) { legend.name = "Терм" }
        }
    })
}

/* Term functions */

fun appendTriangularTerm(
    // input
    fromX: Double,
    toX: Double,
    termName: String,
    // output
    bufferX: MutableList<Double>,
    bufferY: MutableList<Double>,
    bufferTerm: MutableList<String>
) {
    bufferX += listOf(fromX, fromX + (toX - fromX) / 2.0, toX)
    bufferY += listOf(0.0, 1.0, 0.0)
    bufferTerm += List(3) { termName }
}

fun appendTrapezoidalTerm(
    // input
    fromX: Double,
    toX: Double,
    termName: String,
    // output
    bufferX: MutableList<Double>,
    bufferY: MutableList<Double>,
    bufferTerm: MutableList<String>
) {
    bufferX += listOf(
        fromX,
        fromX + (toX - fromX) / 3.0,
        fromX + (toX - fromX) / 3.0 * 2,
        toX
    )
    bufferY += listOf(0.0, 1.0, 1.0, 0.0)
    bufferTerm += List(4) { termName }
}

fun appendParabolicTerm(
    // input
    fromX: Double,
    toX: Double,
    termName: String,
    // output
    bufferX: MutableList<Double>,
    bufferY: MutableList<Double>,
    bufferTerm: MutableList<String>
) {
    val valuesX = (0 until 100).map { fromX + (toX - fromX) / 100 * it }
    val centerX = (toX - fromX) / 2 + fromX
    bufferX += valuesX
    bufferY += valuesX.map { 1 - ((it - centerX) / (centerX - fromX)).pow(2) }
    bufferTerm += List(100) { termName }
}

fun appendGaussianTerm(
    // input
    fromX: Double,
    toX: Double,
    termName: String,
    // output
    bufferX: MutableList<Double>,
    bufferY: MutableList<Double>,
    bufferTerm: MutableList<String>
) {
    val valuesX = (0 until 100).map { fromX + (toX - fromX) / 100 * it }
    val centerX = (toX - fromX) / 2 + fromX
    bufferX += valuesX
    bufferY += valuesX.map {
        val sigma = (centerX - fromX) / 3 // (centerX - fromX) is too big
        val numerator = - (it - centerX).pow(2)
        val denominator = 2 * sigma.pow(2)
        exp(numerator / denominator)
    }
    bufferTerm += List(100) { termName }
}

/* Impl */

val variables: List<LinguisticVariable> = listOf(
    LinguisticVariable(
        userFriendlyName = "PSS-10",
        columnName = "perceived_stress_score",
        termNames = listOf("низкий стресс", "умеренный стресс", "высокий стресс"),
        membershipFunctionType = MembershipFunctionType.TRIANGULAR
    ),

    LinguisticVariable(
        userFriendlyName = "Ежедневное использование соцсети (мин)",
        columnName = "daily_active_minutes_instagram",
        termNames = listOf("немного", "много", "очень много", "вообще не расстаётся с телефоном"),
        membershipFunctionType = MembershipFunctionType.TRIANGULAR
    ),

    LinguisticVariable(
        userFriendlyName = "Лайков поставлено (в день)",
        columnName = "likes_given_per_day",
        termNames = listOf("немного", "много", "очень много"),
        membershipFunctionType = MembershipFunctionType.TRIANGULAR
    ),

    LinguisticVariable(
        userFriendlyName = "Просмотрено reels",
        columnName = "stories_viewed_per_day",
        termNames = listOf("немного", "много", "очень много"),
        membershipFunctionType = MembershipFunctionType.TRIANGULAR
    )
)

variables // display membership functions charts
    .map {
        it to TermChartBuilder(
            when (it.membershipFunctionType) {
                MembershipFunctionType.TRIANGULAR -> ::appendTriangularTerm
                MembershipFunctionType.TRAPEZOIDAL -> ::appendTrapezoidalTerm
                MembershipFunctionType.PARABOLIC -> ::appendParabolicTerm
                MembershipFunctionType.GAUSSIAN -> ::appendGaussianTerm
            }
        )
    }.toMap()
    .forEach(::displayTerms)

fun dataFrameOf(headers: List<String>, cells: List<List<*>>): DataFrame<*> =
    dataFrameOf(headers)(*cells.flatMap { it }.toTypedArray())

DISPLAY( // display table of variables
    dataFrameOf(
        headers = listOf("Переменная", "Столбец", "Минимальное значение", "Максимальное значение"),
        cells = variables.map { listOf(it.userFriendlyName, it.columnName, it.minValue, it.maxValue) }
    )
)

/* Used only by following code blocks */

val inputVariables: List<LinguisticVariable> = variables.drop(1)
val outputVariable: LinguisticVariable = variables.first()

Переменная,Столбец,Минимальное значение,Максимальное значение
PSS-10,perceived_stress_score,0,40
Ежедневное использование соцсети (мин),daily_active_minutes_instagram,5,580
Лайков поставлено (в день),likes_given_per_day,8,350
Просмотрено reels,stories_viewed_per_day,12,150

Определим функции принадлежности, соответствующие графикам каждого терма, а также некоторый программный интерфейс над ними:

In [4]:
/* API */

fun interface MembershipFunction {
    operator fun invoke(x: Double): Double
}

infix fun MembershipFunction.fuzzyOr(function: MembershipFunction) = MembershipFunction { max(this(it), function(it)) }
infix fun MembershipFunction.fuzzyAnd(function: MembershipFunction) = MembershipFunction { min(this(it), function(it)) }

/* Membership functions */

fun interface MembershipFunctionBuilder {
    operator fun invoke(
        fromX: Double,
        toX: Double
    ): MembershipFunction
}

class TriangularMembershipFunction(
    private val fromX: Double,
    private val toX: Double
) : MembershipFunction {
    override fun invoke(x: Double): Double {
        val centerX = fromX + (toX - fromX) / 2.0
        return when {
            x <= fromX -> 0.0
            x <= centerX -> (x - fromX) / (centerX - fromX)
            x < toX -> (toX - x) / (toX - centerX)
            else -> 0.0 // x >= toX
        }
    }
}

class TrapezoidalMembershipFunction(
    private val fromX: Double,
    private val toX: Double
) : MembershipFunction {
    override fun invoke(x: Double): Double {
        val thirdX = fromX + (toX - fromX) / 3.0
        val twoThirdX = fromX + (toX - fromX) / 3.0 * 2
        return when {
            x <= fromX -> 0.0
            x < thirdX -> (x - fromX) / (thirdX - fromX)
            x <= twoThirdX -> 1.0
            x < toX -> (toX - x) / (toX - twoThirdX)
            else -> 0.0 // x >= toX
        }
    }
}

class ParabolicMembershipFunction(
    private val fromX: Double,
    private val toX: Double
) : MembershipFunction {
    override fun invoke(x: Double): Double {
        val centerX = fromX + (toX - fromX) / 2.0
        return 1 - ((x - centerX) / (centerX - fromX)).pow(2)
    }
}

class GaussianMembershipFunction(
    private val fromX: Double,
    private val toX: Double
) : MembershipFunction {
    override fun invoke(x: Double): Double {
        val centerX = fromX + (toX - fromX) / 2.0
        val sigma = (centerX - fromX) / 3 // (centerX - fromX) is too big
        val numerator = - (x - centerX).pow(2)
        val denominator = 2 * sigma.pow(2)
        return exp(numerator / denominator)
    }
}

fun buildEvenTerms( // distribute terms from min to max evenly
    termsCount: Int,
    minValue: Int, maxValue: Int,
    builder: MembershipFunctionBuilder
): List<MembershipFunction> {
    val step = (maxValue - minValue) / (termsCount.toDouble() - 1) * 2
    val fromX = minValue - step / 2

    return List(termsCount) { i ->
        builder(
            fromX + step / 2 * i,
            fromX + step * (i / 2 + 1)
        )
    }
}

/* Used only by following code blocks */

private val columnNameToTermNameToMembershipFunction: Map<String, Map<String, MembershipFunction>> =
    variables.map { variable ->
        val termsMemFuns: List<MembershipFunction> = buildEvenTerms(
            termsCount = variable.termNames.size,
            minValue = variable.minValue,
            maxValue = variable.maxValue,
            builder = MembershipFunctionBuilder(
                when (variable.membershipFunctionType) {
                    MembershipFunctionType.TRIANGULAR -> ::TriangularMembershipFunction
                    MembershipFunctionType.TRAPEZOIDAL -> ::TrapezoidalMembershipFunction
                    MembershipFunctionType.PARABOLIC -> ::ParabolicMembershipFunction
                    MembershipFunctionType.GAUSSIAN -> ::GaussianMembershipFunction
                }
            )
        )
        val termNameToFunction: Map<String, MembershipFunction> =
            variable.termNames
                .zip(termsMemFuns)
                .toMap()

        variable.columnName to termNameToFunction
    }.toMap()

fun getMembershipFunction(columnName: String, termName: String): MembershipFunction =
    columnNameToTermNameToMembershipFunction[columnName]!![termName]!!

operator fun LinguisticVariable.get(termName: String): MembershipFunction =
    columnNameToTermNameToMembershipFunction[columnName]!![termName]!!

Прежде чем реализовать машину нечёткого вывода Мамдани, определим набор правил:

In [5]:
import java.util.HashMap

typealias InputTerms = Map<String, String> // variable to term
data class ExpectedOutput(val confidenceDegree: Double, val termName: String)

// input terms (variable to term) to output term
private val intermediateRules: MutableMap<InputTerms, ExpectedOutput> = HashMap()

learnData.forEach { row ->
    data class TermAndValue(val termName: String, val memFunValue: Double)

    // variable to term
    val termsWithMaxMembership: Map<LinguisticVariable, TermAndValue> = variables.map { variable ->
        val value: Double = (row[variable.columnName] as Number).toDouble() // some cell are parsed as Int, some - as Double
        val termWithMaxMembership: TermAndValue = variable.termNames.asSequence()
            .map { termName ->
                TermAndValue(
                    termName = termName,
                    memFunValue = variable[termName](value)
                )
            }.maxBy(TermAndValue::memFunValue)
        variable to termWithMaxMembership
    }.toMap()

    val inputTerms: InputTerms = termsWithMaxMembership.filterKeys { variable ->
        inputVariables.contains(variable)
    }.map { (variable: LinguisticVariable, termAndValue: TermAndValue) ->
        variable.columnName to termAndValue.termName
    }.toMap()

    val confidenceDegree: Double = termsWithMaxMembership.asSequence()
        .map(Map.Entry<*, TermAndValue>::value)
        .map(TermAndValue::memFunValue)
        .reduce(Double::times)

    if (confidenceDegree > intermediateRules[inputTerms]?.confidenceDegree ?: 0.0)
        intermediateRules[inputTerms] = ExpectedOutput(
            confidenceDegree = confidenceDegree,
            termName = termsWithMaxMembership[outputVariable]!!.termName
        )
}

/* Result */

data class Rule(val inputTerms: InputTerms, val outputTerm: String) {
    override fun toString(): String =
        StringBuilder()
            .append("- ЕСЛИ ")
            .apply {
                inputTerms.asSequence()
                    .flatMap { (columnName, term) ->
                        val userFriendlyName = inputVariables
                            .first { it.columnName == columnName }
                            .userFriendlyName

                        sequenceOf("\"$userFriendlyName\" = \"$term\"", " И ")
                    }.filterIndexed { i: Int, _: String ->
                        i < inputTerms.size * 2 - 1 // drop last "И"
                    }.forEach(this@apply::append)
            }.append(", ТОГДА \"${outputVariable.userFriendlyName}\" = \"$outputTerm\"")
            .toString()
}

val rules: List<Rule> = intermediateRules.map { (input: InputTerms, output: ExpectedOutput) ->
    Rule(inputTerms = input, outputTerm = output.termName)
}.onEach(::println)

private val orderedInputOutputVars = inputVariables + outputVariable
dataFrameOf( // display rules as table
    headers = orderedInputOutputVars.map(LinguisticVariable::userFriendlyName),
    cells = rules.map { rule ->
        inputVariables.map { rule.inputTerms[it.columnName] } + rule.outputTerm
    }
)

- ЕСЛИ "Ежедневное использование соцсети (мин)" = "много" И "Лайков поставлено (в день)" = "много" И "Просмотрено reels" = "немного", ТОГДА "PSS-10" = "умеренный стресс"
- ЕСЛИ "Ежедневное использование соцсети (мин)" = "немного" И "Лайков поставлено (в день)" = "много" И "Просмотрено reels" = "немного", ТОГДА "PSS-10" = "низкий стресс"
- ЕСЛИ "Ежедневное использование соцсети (мин)" = "много" И "Лайков поставлено (в день)" = "немного" И "Просмотрено reels" = "немного", ТОГДА "PSS-10" = "низкий стресс"
- ЕСЛИ "Ежедневное использование соцсети (мин)" = "много" И "Лайков поставлено (в день)" = "много" И "Просмотрено reels" = "много", ТОГДА "PSS-10" = "умеренный стресс"
- ЕСЛИ "Ежедневное использование соцсети (мин)" = "немного" И "Лайков поставлено (в день)" = "немного" И "Просмотрено reels" = "очень много", ТОГДА "PSS-10" = "умеренный стресс"
- ЕСЛИ "Ежедневное использование соцсети (мин)" = "немного" И "Лайков поставлено (в день)" = "немного" И "Просмотрено reels" = "много", ТОГДА "PSS-10" = "низкий стресс"
- ЕСЛИ "Ежедневное использование соцсети (мин)" = "много" И "Лайков поставлено (в день)" = "немного" И "Просмотрено reels" = "очень много", ТОГДА "PSS-10" = "низкий стресс"
- ЕСЛИ "Ежедневное использование соцсети (мин)" = "немного" И "Лайков поставлено (в день)" = "много" И "Просмотрено reels" = "очень много", ТОГДА "PSS-10" = "низкий стресс"
- ЕСЛИ "Ежедневное использование соцсети (мин)" = "очень много" И "Лайков поставлено (в день)" = "очень много" И "Просмотрено reels" = "очень много", ТОГДА "PSS-10" = "высокий стресс"
- ЕСЛИ "Ежедневное использование соцсети (мин)" = "очень много" И "Лайков поставлено (в день)" = "много" И "Просмотрено reels" = "много", ТОГДА "PSS-10" = "высокий стресс"
- ЕСЛИ "Ежедневное использование соцсети (мин)" = "вообще не расстаётся с телефоном" И "Лайков поставлено (в день)" = "очень много" И "Просмотрено reels" = "очень много", ТОГДА "PSS-10" = "высокий стресс"
- ЕСЛИ "Ежедневное использование соцсети (мин)" = "немного" И "Лайков поставлено (в день)" = "немного" И "Просмотрено reels" = "немного", ТОГДА "PSS-10" = "умеренный стресс"
- ЕСЛИ "Ежедневное использование соцсети (мин)" = "очень много" И "Лайков поставлено (в день)" = "много" И "Просмотрено reels" = "очень много", ТОГДА "PSS-10" = "высокий стресс"
- ЕСЛИ "Ежедневное использование соцсети (мин)" = "много" И "Лайков поставлено (в день)" = "много" И "Просмотрено reels" = "очень много", ТОГДА "PSS-10" = "низкий стресс"
- ЕСЛИ "Ежедневное использование соцсети (мин)" = "немного" И "Лайков поставлено (в день)" = "много" И "Просмотрено reels" = "много", ТОГДА "PSS-10" = "низкий стресс"
- ЕСЛИ "Ежедневное использование соцсети (мин)" = "много" И "Лайков поставлено (в день)" = "немного" И "Просмотрено reels" = "много", ТОГДА "PSS-10" = "низкий стресс"

Ежедневное использование соцсети (мин),Лайков поставлено (в день),Просмотрено reels,PSS-10
много,много,немного,умеренный стресс
немного,много,немного,низкий стресс
много,немного,немного,низкий стресс
много,много,много,умеренный стресс
немного,немного,очень много,умеренный стресс
немного,немного,много,низкий стресс
много,немного,очень много,низкий стресс
немного,много,очень много,низкий стресс
очень много,очень много,очень много,высокий стресс
очень много,много,много,высокий стресс
вообще не расстаётся с телефоном,очень много,очень много,высокий стресс
немного,немного,немного,умеренный стресс
очень много,много,очень много,высокий стресс
много,много,очень много,низкий стресс
немного,много,много,низкий стресс
много,немного,много,низкий стресс

Далее, реализуем машину нечёткого вывода [Мамдани](https://docs.exponenta.ru/R2021a_nmtnew/fuzzy/types-of-fuzzy-inference-systems.html).
<br/>Алгоритм следующий:
1. Фаззификация входных значений (получить нечёткие значения).
2. Применяем операцию AND (min).
3. Применяем операцию импликации (min)
    - `A => B = not (A and not B)`.
4. Применить операцию агрегации (max).
5. Дефаззифицируем результат (ищем центроид).

Формула координаты `x` центроида (для непрерывного случая):
$$\bar{x} = \frac{\int x \cdot \mu(x) \, dx}{\int \mu(x) \, dx}$$
Используем метод прямоугольников из численного интегрирования:
$$\bar{x} = \frac{\sum_{i=1}^{n} x_i \cdot \mu(x_i)}{\sum_{i=1}^{n} \mu(x_i)}$$

In [6]:
/**
 * @param inputValues exact values (map of linguistic variable column to its value)
 */
fun fuzzifyImplicateAggregate(inputValues: Map<String, Double>, rules: List<Rule>): MembershipFunction =
    rules.asSequence().map { rule ->
        // apply fuzzy AND (min) to input terms
        val fuzzifiedInputs: Double = rule.inputTerms.minOf { (columnName, termName) ->
            getMembershipFunction(columnName = columnName, termName = termName)(inputValues[columnName]!!)
        }
        // apply implication (min)
        MembershipFunction { x ->
            min(
                fuzzifiedInputs,
                getMembershipFunction(columnName = outputVariable.columnName, termName = rule.outputTerm)(x)
            )
        }
    }.reduce { f1, f2 -> f1 fuzzyOr f2 } // apply aggregation (max)

val MembershipFunction.centroidX: Double get() {
    val steps = 1000
    val xValues = (0 until steps).map {
        outputVariable.minValue + (outputVariable.maxValue - outputVariable.minValue) / steps.toDouble() * it
    }

    val numerator = xValues.asSequence()
        .map { it * this(it) }
        .sum()
    val denominator = xValues.asSequence()
        .map { this(it) }
        .sum()

    return numerator / denominator // find integral using rectangles method
}

fun DataRow<*>.asInputValues(): Map<String, Double> =
    inputVariables.map { variable ->
        val variableValue = (this[variable.columnName] as Number).toDouble()
        variable.columnName to variableValue
    }.toMap()

/* Mamdani fuzzy output machine solution */

// for some rows aggregatedFun(x) = 0, so centroidX is NaN (row 449 e.g.)
private val aggregatedFun: MembershipFunction = fuzzifyImplicateAggregate(
    inputValues = experimentData[100].asInputValues(),
    rules = rules
)
private val centroidX = aggregatedFun.centroidX
println("Mamdani fuzzy output machine result: $centroidX")

// visualize aggregated function and centroidX
private val steps = 1000
private val xLines: List<Double> = (0 until steps).map {
    outputVariable.minValue + (outputVariable.maxValue - outputVariable.minValue) / steps.toDouble() * it
}
private val yLines = xLines.map {
    aggregatedFun(it)
}

plot {
    layout.title = "Результат агрегации и центроид X"

    x.axis.limits = outputVariable.minValue .. outputVariable.maxValue
    y.axis.limits = 0 .. 1

    line {
        x(xLines)
        y(yLines)
        color = Color.BLUE
    }

    points {
        x(listOf(centroidX))
        y(listOf(0))
        color = Color.RED
    }
}

Mamdani fuzzy output machine result: 8.060185969192581

Оценим точность машины, пропустив через неё экспериментальную выборку и вычислив **корень среднеквадратичной ошибки**:
$$RMSE = \sqrt{\dfrac{1}{N}\sum_{i=1}^{N}(y_i - \hat{y}_i)^2}$$

> RMSE (Root Mean Squared Error — корень из среднеквадратичной ошибки) — это метрика качества регрессионных моделей, показывающая среднюю величину отклонения прогнозов от фактических значений. Она измеряется в тех же единицах, что и целевая переменная, чувствительна к крупным ошибкам и чем меньше её значение, тем точнее модель.

По сути это среднеквадратичное отклонение, только относительно остатков (residual - разница между предсказанием и истинным значением), а не среднего:
$$\sigma = \sqrt{\dfrac{1}{N}\sum_{i=1}^{N}(x_i - \bar{x})^2}$$

Средняя абсолютная ошибка:
$$MAE = \frac{1}{n} \sum_{i=1}^{n} |y_i - \hat{y}_i|$$

Средняя абсолютная процентная ошибка:
$$MAPE = \frac{1}{n} \sum_{i=1}^{n} \left| \frac{y_i - \hat{y}_i}{y_i} \right| \times 100\%$$

Область определения PSS от 0 до 40, но деление на 0 невозможно, поэтому для подобного случая используем **взвешенную абсолютную процентную ошибку**:
$$WMAPE = \frac{\sum |y_i - \hat{y}_i|}{\sum |y_i|} \times 100\%$$
или **симметричную абсолютную процентную ошибку**:
$$sMAPE = \frac{1}{n} \sum_{i=1}^{n} \frac{|y_i - \hat{y}_i|}{(|y_i| + |\hat{y}_i|) / 2} \times 100\%$$

In [7]:
/* Run all rows through machine in parallel */

val trueToPredictedValues: List<Pair<Double, Double>> = runBlocking {
    val CHUNK_SIZE = 10_000
    val deferredTrueToPredictedValue: List<Deferred<List<Pair<Double, Double>>>> = experimentData.asSequence()
        .chunked(CHUNK_SIZE)
        .map { chunk ->
            async(context = Dispatchers.IO) {
                chunk.map { row ->
                    val trueValue = (row[outputVariable.columnName] as Number).toDouble()
                    val predictedValue = fuzzifyImplicateAggregate(
                        inputValues = row.asInputValues(),
                        rules = rules
                    ).centroidX

                    trueValue to predictedValue
                }.filterNot { // missing rules can lead to NaN centroid (aggregated function = 0)
                    it.second.isNaN() // skip such rows
                }
            }
        }.toList()

    var trueToPredictedValues = emptyList<Pair<Double, Double>>()
    for (deferredChunk in deferredTrueToPredictedValue)
        trueToPredictedValues += deferredChunk.await()

    trueToPredictedValues
}

/* Quality metrics */

val mse = trueToPredictedValues.asSequence()
    .map { (it.first - it.second).pow(2) }
    .average()

val rmse = mse.pow(0.5)

val mae = trueToPredictedValues.asSequence()
    .map { (it.first - it.second).absoluteValue }
    .average()

private val absTrueValuesSum = trueToPredictedValues.asSequence()
    .map(Pair<Double, *>::first)
    .map(Double::absoluteValue)
    .sum()
val wmape = trueToPredictedValues.asSequence()
    .map { (it.first - it.second).absoluteValue }
    .sum() / absTrueValuesSum * 100

val smape = trueToPredictedValues.asSequence()
    .map { (it.first - it.second).absoluteValue / (it.first.absoluteValue + it.second.absoluteValue) }
    .average() * 200

/* Display */

DISPLAY(dataFrameOf(
    headers = listOf("Метрика", "Значение"),
    cells = listOf(
        listOf("MSE", mse),
        listOf("RMSE", rmse),
        listOf("MAE", mae),
        listOf("WMAPE", "$wmape%"),
        listOf("sMAPE", "$smape%")
    )
))

dataFrameOf(
    headers = (inputVariables + outputVariable)
        .map(LinguisticVariable::userFriendlyName)
        + "Вывод машины"
        + "Абсолютная ошибка",
    cells = experimentData.head(20).map { row ->
        val inputValuesMap = row.asInputValues()

        val inputValues = inputValuesMap.values.toList()
        val outputValue = (row[outputVariable.columnName] as Number).toDouble()
        val machineOutput = fuzzifyImplicateAggregate(
            inputValues = inputValuesMap,
            rules = rules
        ).centroidX
        val absResidual = (outputValue - machineOutput).absoluteValue

        inputValues + outputValue + machineOutput + absResidual
    }
)

Метрика,Значение
MSE,"66,674322"
RMSE,"8,165435"
MAE,"6,487053"
WMAPE,32.485353577233006%
sMAPE,46.61634288694441%

Ежедневное использование соцсети (мин),Лайков поставлено (в день),Просмотрено reels,PSS-10,Вывод машины,Абсолютная ошибка
"311,000000","180,000000","150,000000","37,000000","30,019454","6,980546"
"335,000000","184,000000","150,000000","29,000000","30,135635","1,135635"
"72,000000","54,000000","49,000000","15,000000","8,147921","6,852079"
"112,000000","82,000000","79,000000","8,000000","9,845611","1,845611"
"89,000000","65,000000","68,000000","9,000000","9,080575","0,080575"
"399,000000","245,000000","150,000000","38,000000","31,765812","6,234188"
"336,000000","199,000000","150,000000","38,000000","30,562716","7,437284"
"76,000000","63,000000","68,000000","7,000000","9,080575","2,080575"
"282,000000","157,000000","121,000000","20,000000","31,213173","11,213173"
"114,000000","73,000000","70,000000","14,000000","9,215862","4,784138"
"220,000000","141,000000","112,000000","28,000000","30,585551","2,585551"
"22,000000","35,000000","39,000000","1,000000","8,051882","7,051882"
"99,000000","69,000000","63,000000","1,000000","8,750778","7,750778"
"152,000000","106,000000","75,000000","13,000000","9,561743","3,438257"
"447,000000","246,000000","150,000000","40,000000","31,789773","8,210227"
"231,000000","151,000000","135,000000","25,000000","30,856275","5,856275"
"216,000000","123,000000","112,000000","30,000000","30,485456","0,485456"
"283,000000","152,000000","147,000000","39,000000","31,470153","7,529847"
"180,000000","131,000000","100,000000","30,000000","9,265296","20,734704"
"138,000000","99,000000","94,000000","15,000000","9,526717","5,473283"